name: Update Password

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at 00:00 UTC

jobs:
  update-password:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Select Random Password
        id: select_password
        run: |
          IFS=',' read -r -a passwords <<< "${{ secrets.PASSWORDS }}"
          random_password=${passwords[RANDOM % ${#passwords[@]}]}
          echo "Selected password: $random_password"
          echo "$random_password" > selected_password.txt
          echo "password=$random_password" >> $GITHUB_ENV

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add selected_password.txt
          git commit -m "Update selected password"
          git push
