name: Update Password

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at 00:00 UTC
  workflow_dispatch:     # Manual trigger

jobs:
  update-password:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Service Account Key
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: |
          # Write the service account key to a file
          printf "%s" "$FIREBASE_SERVICE_ACCOUNT_KEY" > "$HOME/firebase_key.json"
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase_key.json"
          
          # Verify file creation and contents
          echo "Service Account Key saved at: $HOME/firebase_key.json"
          ls -l $HOME/firebase_key.json

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Retrieve Weekly Password from Firebase
        run: |
          # Verify Firebase CLI setup and check project
          firebase projects:list
          
          # Retrieve the password from Firebase Realtime Database
          weekly_password=$(firebase database:get /Data/password -P pixelwarnew)
          echo "Weekly password: $weekly_password"
          
          # Save the password to a file
          echo "$weekly_password" > selected_password.txt

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add selected_password.txt
          git commit -m "Update selected password"
          git push
