name: Update Password

on:
  schedule:
    - cron: '0 0 * * 0'  # This runs every Sunday at 00:00 UTC
  workflow_dispatch:     # This allows manual triggering of the workflow

jobs:
  update-password:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Update to the latest version

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Authenticate Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > "${HOME}/firebase_key.json"
          export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/firebase_key.json"

      - name: Retrieve Weekly Password from Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${HOME}/firebase_key.json"
        run: |
          # Retrieve the password from Firebase Realtime Database
          weekly_password=$(firebase database:get /Data/password -P pixelwarnew)
          echo "Weekly password: $weekly_password"
          
          # Save the password to a file
          echo "$weekly_password" > selected_password.txt

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add selected_password.txt
          git commit -m "Update selected password"
          git push
