name: Update Password

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at 00:00 UTC
  workflow_dispatch:     # Manual trigger

jobs:
  update-password:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Service Account Key
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: |
          # Write the service account key to a file
          printf "%s" "$FIREBASE_SERVICE_ACCOUNT_KEY" > "$HOME/firebase_key.json"
          
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or a supported Node.js version

      - name: Install Firebase Admin SDK
        run: npm install firebase-admin

      - name: Retrieve Weekly Password from Firebase
        run: |
          # Create a Node.js script to retrieve password from Firebase
          cat << 'EOF' > retrieve-password.js
          const admin = require('firebase-admin');
          const fs = require('fs');

          // Initialize Firebase Admin SDK
          admin.initializeApp({
            credential: admin.credential.cert(process.env.GOOGLE_APPLICATION_CREDENTIALS),
            databaseURL: "https://pixelwarnew.firebaseio.com"  // Replace with your database URL
          });

          // Reference to Firebase Realtime Database
          const db = admin.database();

          // Retrieve the weekly password
          db.ref('/Data/password').once('value', (snapshot) => {
            const weeklyPassword = snapshot.val();
            console.log("Weekly password:", weeklyPassword);
            
            // Save the password to a file
            fs.writeFileSync('selected_password.txt', weeklyPassword);
          }).catch((error) => {
            console.error("Error retrieving password:", error);
            process.exit(1); // Exit with error code for GitHub Actions
          });
          EOF

          # Run the Node.js script
          node retrieve-password.js

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add selected_password.txt
          git commit -m "Update selected password"
          git push
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase_key.json
