name: Update Password

on:
  schedule:
    - cron: '0 0 * * 0'  # This runs every Sunday at 00:00 UTC

jobs:
  update-password:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Update to the latest version

      - name: Select Random Password
        id: select_password
        run: |
          # List of passwords stored in the Firebase database, fetched using Firebase CLI
          passwords=("A1bC2" "D3eF4" "G5hI6" "J7kL8" "M9nO0"
                     "P1qR2" "S3tU4" "V5wX6" "Y7zA8" "B9cD0"
                     "E1fG2" "H3iJ4" "K5lM6" "N7oP8" "Q9rS0"
                     "T1uV2" "W3xY4" "Z5aB6" "C7dE8" "F9gH0"
                     "I1jK2" "L3mN4" "O5pQ6" "R7sT8" "U9vW0"
                     "X1yZ2" "A3bC4" "D5eF6" "G7hI8" "J9kL0"
                     "M1nO2" "P3qR4" "S5tU6" "V7wX8" "Y9zA0"
                     "B1cD2" "E3fG4" "H5iJ6" "K7mN8" "N9oP0"
                     "Q1rS2" "T3uV4" "W5yZ6" "Z7aB8" "C9dE0"
                     "F1gH2" "I3jK4" "L5mN6" "O7pQ8" "R9sT0"
                     "U1vW2" "X3yZ4" "A5bC6" "D7eF8" "G9hI0"
                     "J1kL2" "M3nO4" "P5qR6" "S7tU8" "V9wX0"
                     "Y1zA2" "B3cD4" "E5fG6" "H7iJ8" "K9lM0"
                     "N1oP2" "Q3rS4" "T5uV6" "W7yZ8" "Z9aB0"
                     "C1dE2" "F3gH4" "I5jK6" "L7mN8" "O9pQ0"
                     "R1sT2" "U3vW4" "X5yZ6" "A7bC8" "D9eF0"
                     "G1hI2" "J3kL4" "M5nO6" "P7qR8" "S9tU0"
                     "V1wX2" "Y3zA4" "B5cD6" "E7fG8" "H9iJ0"
                     "K1lM2" "N3oP4" "Q5rS6" "T7uV8" "W9yZ0")
          
          # Randomly select a password
          random_password="${passwords[RANDOM % ${#passwords[@]}]}"
          echo "Selected password: $random_password"
          
          # Save the random password to a file
          echo "$random_password" > selected_password.txt

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add selected_password.txt
          git commit -m "Update selected password"
          git push
