name: Update Password

on:
  schedule:
    - cron: '0 0 * * 0'  # This runs every Sunday at 00:00 UTC

jobs:
  update-password:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Select Random Password
        id: select_password
        run: |
          # Split the passwords from Firebase into an array
          IFS=',' read -r -a passwords <<< "${{ secrets.PASSWORDS }}"

          # Get a random password from the array
          random_password=${passwords[RANDOM % ${#passwords[@]}]}

          echo "Selected password: $random_password"

          # Save the random password to an environment file
          echo "RANDOM_PASSWORD=$random_password" >> $GITHUB_ENV

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo "$RANDOM_PASSWORD" > selected_password.txt
          git add selected_password.txt
          git commit -m "Update selected password"
          git push
